# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'PxView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PxView
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'


end
