fastlane_version "2.58.0"

default_platform :ios

platform :ios do
  lane :beta do |values|
    gym(scheme: 'PxView', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['jesse@itjesse.com', 'legend.t@icloud.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'a5cd22f124edbc008d9649ff4a4b7fb510c6132a',
             build_secret: '8139ed2ad3ef34daf22e135e8cb17011e08dac308876996db26dbc6986184227',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

  end

  lane :screenshots do
    snapshot
    frameit
    deliver
  end
  lane :upload do
    deliver(
      username: "jesse@itjesse.com",
      app_identifier: "com.itjesse.pxview",
      include_in_app_purchases: false,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_app_version_update: true)
  end
end
